<a href="https://colab.research.google.com/github/SachinScaler/DAV1Aug24/blob/main/Numpy_2%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Solution for NUMPY 1 HW CaseStudy

#### NPS steps:
1) read file into numpy array

2) calculate count of detractors and promoters via Bool Index

3) calculate %

4) Calculate and round off by 2 decimal places and print NPS

In [ ]:
import numpy as np

# score_data = np.loadtxt('https://raw.githubusercontent.com/SachinScaler/DAV1Aug24/main/survey.txt')
# score_data.shape

(1167,)

In [ ]:
import numpy as np

# Step 1: read file into numpy array: using raw github link. you can upload in colab and read as well
data = np.loadtxt('https://raw.githubusercontent.com/SachinScaler/DAV1Aug24/main/survey.txt')
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [ ]:
# Step 2: calculate count of detractors and promoters via Bool Index

detractors = data[data <= 6]
# Number of detractors
num_detractors = len(detractors)
print("Number of detractors",num_detractors)

promoters = data[data >= 9]
# Number of promoters
num_promoters = len(promoters)
print("Number of promoters", num_promoters)

Number of detractors 332
Number of promoters 609


In [ ]:
# Step 3: calculate %
percentage_detractors = (num_detractors/len(data)) * 100
print("Percentage of detractors", percentage_detractors)

percentage_promoters = (num_promoters/len(data)) * 100
print("Percentage of promoters", percentage_promoters)

Percentage of detractors 28.449014567266495
Percentage of promoters 52.185089974293064


In [ ]:
# Step 4: Calculate and round off by 2 decimal places and print NPS
nps = percentage_promoters - percentage_detractors
print("NPS:", round(nps,2))

NPS: 23.74


## Working with 2-D arrays (Matrices)


In [ ]:
import numpy as np

mat = np.array([[1,2,3,4], [4,5,6,7]])
mat

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
# Method2: start with 1 d array and reshape into 2d (nd) array
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr.shape, arr.ndim

((16,), 1)

In [ ]:
mat = arr.reshape(4,4)
mat.shape, mat.ndim

((4, 4), 2)

In [ ]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
mat = arr.reshape(8,2)
mat

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
mat = arr.reshape(8, -1)
mat

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
mat = arr.reshape(-1, 8)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
mat.shape

(2, 8)

In [ ]:
mat.ndim

2

In [ ]:
len(mat)

2

#### Transpose

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
mat.T

array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

### Indexing

In [ ]:
m1 = np.arange(1,10).reshape((3,3))
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1[0][1]

2

In [ ]:
# this works only in numpy
m1[0, 1]

2

In [ ]:
m1[1, 2] # m[1][2]

6

In [ ]:
arr = np.array([100,200,300,400,500,600])
arr[1, 2] # Matrix indexing

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
index = [1, 2]
arr[index] # multiple indexing: m1[[1, 2]]

array([200, 300])

In [ ]:
m1[1,2]

6

In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
index = [[1, 2],[1,2]]
m1[index]

array([[[4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [ ]:
index = [0, 1, 2]
m1[index]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# let's select all rows


In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Select only 2nd col of all rows

In [ ]:
m1[:, 1]

array([2, 5, 8])

In [ ]:
m1[1, :]

array([4, 5, 6])

# select first two rows

In [ ]:
m1[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m1[:2, -2:] # first two rows and last 2 cols

array([[2, 3],
       [5, 6]])

Question: first two rows and last 2 cols
```
python_list =
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

```

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
print(a[3:])

[4, 5]


In [ ]:
print(b[::-2])

[6, 8]


In [ ]:
a[3:] = b[::-2]
print(a)


[1, 2, 3, 6, 8]


In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1[:, 1] = -1
m1

array([[ 1, -1,  3],
       [ 4, -1,  6],
       [ 7, -1,  9]])

### Fancy Indexing or masking in 2d Array

In [ ]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
arr = np.arange(12)
arr < 6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[arr < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
# True indexes are filtered
m1[m1 < 7] # output will be 1d

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# masking to select and overwrite
a = np.array([0,1,2,3,4,5])
# mask = (a%2 == 0)
# a[mask] = -1

In [ ]:
(a%2 == 0)

array([ True, False,  True, False,  True, False])

In [ ]:
a[a%2 == 0]

array([0, 2, 4])

In [ ]:
a[a%2 == 0] = - 1

# Aggregate Functions

In [89]:
a1 = np.arange(12)
m1 = np.arange(12).reshape(3, 4)
a1, m1

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [90]:
np.sum(a1)

66

In [91]:
np.sum(m1)

66

In [92]:
np.min(m1)

0

min, max, sum, mean, std

In [93]:
np.mean(m1)

5.5

In [94]:
np.mean(a1)

5.5

In [94]:
# sum(nums/len(nums)

In [95]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.mean(m1, axis = 1) # for each row, col changes hence axis = 1

array([1.5, 5.5, 9.5])

### Logical Operations in numpy

- any

In [108]:
import numpy as np

# Prices of items on your shopping list
prices = np.array([50, 45, 25, 20, 35])

# Your budget
budget = 30

In [109]:
prices <= budget

array([False, False,  True,  True, False])

In [110]:
# Check if there's at least one item you can afford
can_afford = np.any(prices <= budget)
can_afford

True

In [113]:
if can_afford:
    print("You can buy at least one item on your list!")
else:
    print("Sorry, nothing on your list fits your budget.")

You can buy at least one item on your list!


In [111]:
# Check we buy all items
budget = 30
can_afford = np.all(prices <= budget)
can_afford

False

In [112]:
# Check we buy all items
budget = 50
can_afford = np.all(prices <= budget)
can_afford

True

In [97]:
np.mean(m1[0])

1.5

In [98]:
np.mean(m1, axis = 1)[0]

1.5

In [100]:
m1[0]

array([0, 1, 2, 3])

In [101]:
np.mean(m1,axis=1)


array([1.5, 5.5, 9.5])

In [99]:
np.mean(m1, axis = 0) # for columnwise mean, row is changing hence axis = 0

array([4., 5., 6., 7.])

In [102]:
np.mean(m1[:, 1]) # for columnwise mean, row is changing hence axis = 0

5.0

In [103]:
np.sum(m1, axis = 0) # for columnwise mean, row is changing hence axis = 0

array([12, 15, 18, 21])

In [104]:
np.min(m1, axis = 0) # for columnwise mean, row is changing hence axis = 0

array([0, 1, 2, 3])

# experiment with 3D: 0,1, 2

* **axis = 1**: Changes will happen along the horizontal axis

* **axis = 0**: Changes will happen along the vertical axis


where

In [ ]:
# apply 10% discount hwere prices are more than 50 Dollars

In [114]:
import numpy as np

# Product prices
prices = np.array([45, 55, 60, 75, 40, 90])
prices * 0.9

array([40.5, 49.5, 54. , 67.5, 36. , 81. ])

In [117]:
prices = np.array([45, 55, 60, 75, 40, 90])


cond = prices > 50
disc_price = np.where(cond, prices * 0.9, prices)
disc_price

array([45. , 49.5, 54. , 67.5, 40. , 81. ])

In [118]:
print(np.where(cond, prices * 0.9, prices))

[45.  49.5 54.  67.5 40.  81. ]


In [119]:
print(np.where(cond)) # no x and y hence only indexes

(array([1, 2, 3, 5]),)


In [124]:
# element wise comparison
a = np.array([0,2,3])
b = np.array([1,3,5])

a >= b

array([False, False, False])

In [125]:
np.any(a >= b)

False

In [126]:
np.all(a >= b)

False

### Use Case: Fitness data analysis
Imagine you are a Data Scientist at Fitbit

You've been given a user data to analyse and find some insights which can be shown on the smart watch.

But why would we want to analyse the user data for desiging the watch?

These insights from the user data can help business make customer oriented decision for the product design.

In [128]:
# download data
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 8.18MB/s]


### EDA
Exploratory Data Analysis (EDA) is a process of examining, summarizing, and visualizing data sets to understand their main characteristics, uncover patterns that helps analysts and data scientists gain insights into the data, make informed
decisions, and guide further analysis or modeling.

In [129]:
data = np.loadtxt('/content/fit.txt', dtype='str')
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [130]:
print(data.shape, data.ndim)

(96, 6) 2


We can see that this is a 2-dimensional list.

There are 96 records and each record has 6 features.

These features are:

- Date
- Step Count
- Mood
- Calories Burned
- Hours of Sleep
- Activity Status

### Task: Compare avg number of steps across each type of mood
- How many unique mood values are there

and there is a relation in moods and stepcount

- which date the user walked maximum

In [131]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
m1[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [133]:
m1[-2:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
m1[:2,-2:]

array([2, 6])

linspace

In [139]:
np.linspace(10, 50, 20)

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

## For whatsapp group: 8586 83 6627

In [140]:
scores = np.array([20, 35, 68, 82, 83, 70, 90])


marks >= 80 : Distinction

60 <= marks < 80 : First Division

In [142]:
scores[scores >= 80]

array([82, 83, 90])

In [150]:
scores[(60 <= scores) & (scores < 80)]

array([68, 70])

In [153]:
scores[(60 <= scores) | (scores < 80)] # | or condition

array([20, 35, 68, 82, 83, 70, 90])

In [157]:
m1[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [156]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])