<a href="https://colab.research.google.com/github/SachinScaler/DAV1Aug24/blob/main/Numpy_4%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.arange(4)
print(a)

[0 1 2 3]


In [2]:
b = a.reshape(2,2) # shallow copy
print(b)

[[0 1]
 [2 3]]


In [3]:
a[0] = 100 # we modified a[0]
print(a)

[100   1   2   3]


In [4]:
print(b) # b[0][0] got modified

[[100   1]
 [  2   3]]


In [5]:
a = np.arange(4)
print(a)

b = a + 2 # deepcopy
print(b)

[0 1 2 3]
[2 3 4 5]


In [6]:
a[0] = 100
print("a", a)
print("b", b)

a [100   1   2   3]
b [2 3 4 5]


### Slicing:

In [12]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [14]:
b[1]= 1000
print(b)

[   0 1000    4    6    8]


In [15]:
print(a)

[   0    1 1000    3    4    5    6    7    8    9]


In [9]:
np.shares_memory(a, b)

True

- True: Shallow copy

In [10]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = a + 0
np.shares_memory(a, b)

False

- False i.e Deep Copy

### Mask

In [16]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
mask = a % 2 == 0
b = a[mask]

In [18]:
np.shares_memory(a, b)

False

- shallow copy: reshape and slicing
- deepcopy: arth ops, masking


In [21]:
# doesn't work on lists
a = [0,1,2]
b = a

np.shares_memory(a, b)

False

In [22]:
a[0] = 10
print(b)

[10, 1, 2]


In [23]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0] # deep copy
b[0] = 10
a[:2] # 0 and 1

array([0, 1])

In [24]:
a = [0,1,2,3,4,5]
b = a[a%1 == 0] #masking doesn't work in list
b[0] = 10
a[:2]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

### shallow copy can be created using .view() method

In [25]:
a = np.arange(10)

In [26]:
s_copy = a.view()

In [27]:
s_copy[4] = 20

In [28]:
print(a)
print(s_copy)

[ 0  1  2  3 20  5  6  7  8  9]
[ 0  1  2  3 20  5  6  7  8  9]


In [29]:
np.shares_memory(a, s_copy)

True

In [35]:
s_copy[4] = 20.9
s_copy

array([ 0,  1,  2,  3, 20,  5,  6,  7,  8,  9])

In [36]:
s_copy.dtype

dtype('int64')

### .copy() method tries to create a deepcopy of data

In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
b = a.copy() # will create a deepcopy since it's homogeneous arr
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
np.shares_memory(a, b)

False

### Splitting Array
- np.split
    - integers
    - list

- It takes an argument indices_or_sections.
- If indices_or_sections is an integer, n, the array will be divided into n equal arrays along axis.
- If such a split is not possible, an error is raised.
- If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split.
- If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.

In [41]:
x = np.arange(9)
print(x, len(x))

[0 1 2 3 4 5 6 7 8] 9


In [43]:
splitted_list = np.split(x, 3)
splitted_list

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [44]:
splitted_list[0]

array([0, 1, 2])

In [45]:
splitted_list[1]

array([3, 4, 5])

In [46]:
splitted_list[2]

array([6, 7, 8])

In [47]:
print(x)
splitted_list = np.split(x, 2)
splitted_list

[0 1 2 3 4 5 6 7 8]


ValueError: array split does not result in an equal division

In [48]:
x = np.arange(9)
splitted_list = np.split(x, [4])
splitted_list

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8])]

In [49]:
x = np.arange(9)
splitted_list = np.split(x, [4, 7])
splitted_list

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

splits the array into three parts:
- part 1: all element before index 4
- part 2: all elements before 7 and after 4 (4 included)
- part3: all elements after 7 included

###

In [50]:
x = np.arange(16.0).reshape(4, 4)
x.shape

(4, 4)

In [51]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [53]:
x.ndim

2

- hsplit: divides array on horizontal axis
- vsplit: divides array in vertical axis

In [54]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [55]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [57]:
np.split(x, 2) # last axis i.e. vertical split

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [60]:
np.vsplit(x, [3])

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

### Stacking:
- vstack
- hstack
- concatenate: can be used for both vstack and hstack by specifying axis

In [62]:
a = np.array([1, 5])# len of row== num_cols
b = np.array([2, 6])
c = np.array([3, 7])
print(a)
print(b)
print(c)

[1 5]
[2 6]
[3 7]


In [65]:
'''
[[1, 5],
 [2, 6],
 [3, 7]
]
'''

np.vstack([a, b, c])

array([[1, 5],
       [2, 6],
       [3, 7]])

In [67]:
a=np.array([1,5,1])
b=np.array([2,6,1])
c=np.array([3,7])

print(np.vstack((a,b,c)))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [73]:
a = np.arange(10, 15).reshape(5, 1)
a

array([[10],
       [11],
       [12],
       [13],
       [14]])

In [74]:
a.shape

(5, 1)

In [75]:
b = np.arange(15).reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [76]:
b.shape

(5, 3)

In [77]:
np.hstack([a,b])

array([[10,  0,  1,  2],
       [11,  3,  4,  5],
       [12,  6,  7,  8],
       [13,  9, 10, 11],
       [14, 12, 13, 14]])

concatenate:
expects you to pass all arrays of same dimension

In [84]:
a = np.array([[10,11,12]]) # 2 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.concatenate((a, b), axis = 0)

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [85]:
a = np.array([10,11,12]) # 1 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim

np.concatenate((a, b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [86]:
a = np.array([[10,11,12]]) # 2 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.vstack((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [87]:
a = np.array([10,11,12]) # 1 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.vstack((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [90]:
a = np.array([[10,11,12]]) # 2 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.concatenate((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [92]:
b = np.array([[1,2,3], [4,5,6]]) # 2 dim

print(b)

[[1 2 3]
 [4 5 6]]


In [93]:
b[0]

array([1, 2, 3])

In [94]:
b[1]

array([4, 5, 6])

In [95]:
b[:, 0]

array([1, 4])

### In Concatenate we can pass axis values:
- axis 0:rowwise stacking: vstack
- axis 1:columnwise stack: hstack


In [96]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [97]:
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# @ and matmul are exactly same
# np.dot: support scalar multiplication as well

In [100]:
list1 = [1,2,3]
list2 = [5,6]

print(list1 + list2)

[1, 2, 3, 5, 6]


In [101]:
list1.extend(list2)
list1

[1, 2, 3, 5, 6]

Day3: "rotate Image" additional Q:2

https://leetcode.com/problems/rotate-image/description/

In [102]:
arra = [10, 13, 9, 6]

In [103]:
np.max(arra)

13

In [105]:
np.argmax(arra) # arg variations of functions return index

1

In [107]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0] #
np.shares_memory(a, b)

False

In [108]:
b[0] = 10

In [109]:
print(a)

[0 1 2 3 4 5]


In [110]:
a[:2]

array([0, 1])

In [111]:
a = np.array([0,1,2,3,4,5])
b = a[:2] # shallow copy
b[0] = 1
a[:2]

array([1, 1])

In [113]:
list1=[1,2,3,4,5,6,7,8,9]
list2=[]
for i in range(0,len(list1),3):
    list2.append(list1[i:i+3])
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [114]:
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
v = np.array([200,300,400])
v[:,None]

array([[200],
       [300],
       [400]])

In [116]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])

In [117]:
x/v[:,None][1][1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- even if we remove None ans would be same

In [ ]:
[[200, 200, 200],
 [300, 300, 300],
 [400, 400, 400]])