<a href="https://colab.research.google.com/github/SachinScaler/DAV1Aug24/blob/main/Numpy_3%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Sorted

In [1]:
import numpy as np

a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [2]:
a.sort()

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
sorted(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [6]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [17]:
import numpy as np

a = np.array([[11,50,3], [200,5,7], [400, 250, 300]])
a

array([[ 11,  50,   3],
       [200,   5,   7],
       [400, 250, 300]])

In [18]:
a = sorted(a, key = lambda x :x[1])
a

[array([200,   5,   7]), array([11, 50,  3]), array([400, 250, 300])]

In [19]:
np.sort(a)

array([[  5,   7, 200],
       [  3,  11,  50],
       [250, 300, 400]])

In [21]:
a = np.array([[11,50,3], [200,5,7], [400, 250, 300]])
a

array([[ 11,  50,   3],
       [200,   5,   7],
       [400, 250, 300]])

In [24]:
np.sort(a, axis = 0) # sorting every column

array([[ 11,   5,   3],
       [200,  50,   7],
       [400, 250, 300]])

In [25]:
a

array([[ 11,  50,   3],
       [200,   5,   7],
       [400, 250, 300]])

In [30]:
np.sort(a, axis = 1) # sorting every row

array([[  3,  11,  50],
       [  5,   7, 200],
       [250, 300, 400]])

In [33]:
np.sort(a, axis = 1)  # sorting every row

array([[  3,  11,  50],
       [  5,   7, 200],
       [250, 300, 400]])

### How can i sort entire matrix:

Expected:

[[  3,  5, 7],
[  11,   50, 200],
[250, 300, 400]]

```

axis = - 1 # default axis: last
a.ndim-> 0 and 1


ndim = 2
axis = 1


ndim = 3
axis = 2
```

In [ ]:
#np.sort(a) --> np.sort(a, axis = 1)

In [38]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])
b = np.sort(a)
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


In [ ]:
a[0][0]

Matrix Multiplication

In [41]:
d = np.arange(12).reshape(3, 4)
e = np.arange(13, 25).reshape(3, 4)

In [42]:
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
print(e)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [44]:
d * e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [45]:
a = np.arange(1,13).reshape((3,4))
c = np.arange(2,14).reshape((4,3))

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
print(c)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [48]:
a.shape, c.shape

((3, 4), (4, 3))

In [49]:
np.dot(a, c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [50]:
np.matmul(a, c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [51]:
a @ c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

np.dot(a, c): you can pass either a or b as scaler as well

In [52]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
np.dot(a, 5)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [54]:
a @ 5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [55]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [56]:
3 + 1j

(3+1j)

In [57]:
A = np.arange(10).reshape(5,2)
B = np.arange(2).reshape(2,1)
print(np.dot(A,B))

[[1]
 [3]
 [5]
 [7]
 [9]]


In [58]:
print(np.dot(A,B).shape)

(5, 1)


### Vectorization

In [10]:
import numpy as np

a = np.arange(10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [11]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2
    return x

random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
%%timeit
for i in range(len(a)):
    a[i] = random_operation(a[i])
a

5.39 ms ± 86.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
a  % 2  == 0

In [ ]:
if a  % 2  == 0:
    pass


In [ ]:
a = np.arange(10)
a

In [7]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2

    return x


vec_func = np.vectorize(random_operation)

In [8]:
%%timeit
# np.vectorize takes any function and returns it's vectorized version of function
vec_func(a)

3.09 s ± 525 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
@np.vectorize
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2

    return x

In [17]:
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3]


In [18]:
print(A+B)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [19]:
A = np.arange(12).reshape(4, 3)
B = np.array([1, 2, 3])
print(A)
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 2 3]


In [20]:
print(A + B)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [21]:
A = np.arange(12).reshape(4, 3)
B = 5
print(A)
print(B)
print(A + B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
5
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [22]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
A[0] # sort this row? col

array([0, 1, 2])

In [24]:
A[1] # sort this row? col

array([3, 4, 5])

In [ ]:
# axis = 0 rows
# axis = 1 rows # last axis

In [25]:
np.sort(A)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- column wise comparision will end up as rowwise sorted

In [ ]:
# perform the below task on a using np.where: refer previous session
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2

    return x



In [26]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
A[-3 : -1, -1]

array([5, 8])

arr[-5:-1 , -1]



In [36]:
array = np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])

# row, col
array[ [0,1,2], [0,1,2]]

array([0, 4, 8])

 #Given a List of numbers, reshape it into a 2D array with specified dimensions.**

 ```
input: [1, 2, 3, 4, 5, 6, 7, 8, 9]
desired shape: (3, 3)
output: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
``` how to convert this into 2d using simple list operations.

In [49]:
row_num = 0

col_size = 3

[1, 2, 3, 4, 5, 6, 7, 8, 9][row_num: (row_num + 1) * col_size]
# [1, 2, 3, 4, 5, 6, 7, 8, 9][0:3]

[1, 2, 3]

In [50]:
row_num = 1
[1, 2, 3, 4, 5, 6, 7, 8, 9][row_num *3: (row_num + 1) *col_size]
#[1, 2, 3, 4, 5, 6, 7, 8, 9][3:6]

[4, 5, 6]

In [51]:
row_num = 2
[1, 2, 3, 4, 5, 6, 7, 8, 9][row_num *3: (row_num + 1) *col_size]

[7, 8, 9]

In [53]:
list1 = [1,2,3]
list2 = [1,2,3]

list3 = [x + y for x, y in zip(list1, list2)]
list3

[2, 4, 6]

In [59]:
list_len1=int(input("Enter the length of the first array: "))
list1=[]

for i in range(list_len1):
    list1.append(int(input(f"Enter value for list1 element {i}:")))


Enter the length of the first array: 2
Enter value for list1 element 0:10
Enter value for list1 element 1:5


In [60]:
list1

[10, 5]

In [61]:
list_len2 = int(input("Enter the length of the first array: "))
list2=[]

for i in range(list_len2):
    list2.append(int(input(f"Enter value for list2 element {i}:")))

Enter the length of the first array: 2
Enter value for list2 element 0:1
Enter value for list2 element 1:6


In [62]:
list3 = [x + y for x, y in zip(list1, list2)]
list3

[11, 11]

In [64]:
list(map(lambda x, y: x + y, list1, list2))

[11, 11]

In [66]:
for i in range(list_len2):
    print(list1[i],list2[i])

10 1
5 6


map -> list

In [72]:
start = 5
length = 10
step = 3
for i in range(1,length + 1):
    print(start + (i-1)*step)

5
8
11
14
17
20
23
26
29
32


In [87]:
np.linspace(start, start + (length - 1)*step, length )

array([ 5.,  8., 11., 14., 17., 20., 23., 26., 29., 32.])

In [85]:
len(np.linspace(start, start + (length - 1)*step, length ))

10

In [89]:
np.linspace(5, 32, 10)

array([ 5.,  8., 11., 14., 17., 20., 23., 26., 29., 32.])

In [90]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])


In [91]:
p + q

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [92]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# [r, c]
#[1:-1,1:-1]

# r -> 1:-1