<a href="https://colab.research.google.com/github/SachinScaler/DAV1Aug24/blob/main/Pandas_1%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas # command line terminal remove !

In [2]:
import pandas as pd

In [3]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2024-08-27 01:43:59--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 74.125.137.101, 74.125.137.139, 74.125.137.102, ...
Connecting to drive.google.com (drive.google.com)|74.125.137.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2024-08-27 01:43:59--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 74.125.137.132, 2607:f8b0:4023:c03::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|74.125.137.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    i

In [4]:
# read csv as dataframe as store it into df variable
df = pd.read_csv("mckinsey.csv")

In [5]:
df.head() # first 5 elements of df

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [7]:
df.shape

(1704, 6)

In [6]:
df.head(20)

country  year  population continent  life_exp      gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801   779.445314
1   Afghanistan  1957     9240934      Asia    30.332   820.853030
2   Afghanistan  1962    10267083      Asia    31.997   853.100710
3   Afghanistan  1967    11537966      Asia    34.020   836.197138
4   Afghanistan  1972    13079460      Asia    36.088   739.981106
5   Afghanistan  1977    14880372      Asia    38.438   786.113360
6   Afghanistan  1982    12881816      Asia    39.854   978.011439
7   Afghanistan  1987    13867957      Asia    40.822   852.395945
8   Afghanistan  1992    16317921      Asia    41.674   649.341395
9   Afghanistan  1997    22227415      Asia    41.763   635.341351
10  Afghanistan  2002    25268405      Asia    42.129   726.734055
11  Afghanistan  2007    31889923      Asia    43.828   974.580338
12      Albania  1952     1282697    Europe    55.230  1601.056136
13      Albania  1957     1476505    Europe    59.280  1942.284244
14      Albania  1962     1728137    Europe    64.820  2312.888958
15      Albania  1967     1984060    Europe    66.220  2760.196931
16      Albania  1972     2263554    Europe    67.690  3313.422188
17      Albania  1977     2509048    Europe    68.930  3533.003910
18      Albania  1982     2780097    Europe    70.420  3630.880722
19      Albania  1987     3075321    Europe    72.000  3738.932735

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [11]:
type(df['year'])

pandas.core.series.Series

In [13]:
df['year'][4]

1972

In [14]:
df['country'][:5]

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [15]:
df['country'].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [16]:
df['country', 'year']

KeyError: ('country', 'year')

In [17]:
cols = ['country', 'year']
df[cols] # this a df

country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

In [18]:
df[['country']]

country
0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
...           ...
1699     Zimbabwe
1700     Zimbabwe
1701     Zimbabwe
1702     Zimbabwe
1703     Zimbabwe

[1704 rows x 1 columns]

In [20]:
df['year']

0       1952
1       1957
2       1962
3       1967
4       1972
        ... 
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [21]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [23]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

### Creating DF from scratch:
https://colab.research.google.com/drive/1x3ct95RtIIQTJeGbyuuYaMociVp90ww6?usp=sharing

In [28]:
dict_users = {
                "userid":[1, 2, 3, 4],
                "name":["sharadh", "shahid", "khusalli", None]
              }

type(dict_users)

dict

In [29]:
pd.DataFrame(dict_users)

userid      name
0       1   sharadh
1       2    shahid
2       3  khusalli
3       4      None

# Columns

In [30]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [31]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [32]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [33]:
df[['country']]

country
0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
...           ...
1699     Zimbabwe
1700     Zimbabwe
1701     Zimbabwe
1702     Zimbabwe
1703     Zimbabwe

[1704 rows x 1 columns]

### Unique values in series

In [34]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [38]:
len(df['country'].unique())

142

In [39]:
df['country'].nunique()

142

In [44]:
df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [37]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

### Rename columns
We can rename the column by

1) passing the dictionary with old_name:new_name pair

2) specifying axis=1

In [45]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [46]:
dict1 = {"population": "countofpeople", "life_exp": "life_expectancy"}


In [48]:
df.rename(columns=dict1)  # rename the column index

country  year  countofpeople continent  life_expectancy     gdp_cap
0     Afghanistan  1952        8425333      Asia           28.801  779.445314
1     Afghanistan  1957        9240934      Asia           30.332  820.853030
2     Afghanistan  1962       10267083      Asia           31.997  853.100710
3     Afghanistan  1967       11537966      Asia           34.020  836.197138
4     Afghanistan  1972       13079460      Asia           36.088  739.981106
...           ...   ...            ...       ...              ...         ...
1699     Zimbabwe  1987        9216418    Africa           62.351  706.157306
1700     Zimbabwe  1992       10704340    Africa           60.377  693.420786
1701     Zimbabwe  1997       11404948    Africa           46.809  792.449960
1702     Zimbabwe  2002       11926563    Africa           39.989  672.038623
1703     Zimbabwe  2007       12311143    Africa           43.487  469.709298

[1704 rows x 6 columns]

In [49]:
df.rename(dict1, axis = 1)  # rename the column index

country  year  countofpeople continent  life_expectancy     gdp_cap
0     Afghanistan  1952        8425333      Asia           28.801  779.445314
1     Afghanistan  1957        9240934      Asia           30.332  820.853030
2     Afghanistan  1962       10267083      Asia           31.997  853.100710
3     Afghanistan  1967       11537966      Asia           34.020  836.197138
4     Afghanistan  1972       13079460      Asia           36.088  739.981106
...           ...   ...            ...       ...              ...         ...
1699     Zimbabwe  1987        9216418    Africa           62.351  706.157306
1700     Zimbabwe  1992       10704340    Africa           60.377  693.420786
1701     Zimbabwe  1997       11404948    Africa           46.809  792.449960
1702     Zimbabwe  2002       11926563    Africa           39.989  672.038623
1703     Zimbabwe  2007       12311143    Africa           43.487  469.709298

[1704 rows x 6 columns]

### Create a new column
1) Use existing column to create a new col

2) Create new col from new data

In [53]:
df['year'] + 10  # create a new series using existing series

0       1962
1       1967
2       1972
3       1977
4       1982
        ... 
1699    1997
1700    2002
1701    2007
1702    2012
1703    2017
Name: year, Length: 1704, dtype: int64

In [51]:
# df['newcolname'] = series/array/list of same size
df['year+10'] = df['year'] + 10

In [52]:
df.head()

country  year  population continent  life_exp     gdp_cap  year+10
0  Afghanistan  1952     8425333      Asia    28.801  779.445314     1962
1  Afghanistan  1957     9240934      Asia    30.332  820.853030     1967
2  Afghanistan  1962    10267083      Asia    31.997  853.100710     1972
3  Afghanistan  1967    11537966      Asia    34.020  836.197138     1977
4  Afghanistan  1972    13079460      Asia    36.088  739.981106     1982

In [54]:
# delete a column: axis = 1
df.drop('year+10', axis=1)

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

resume 8:28

In [55]:
df

country  year  population continent  life_exp     gdp_cap  year+10
0     Afghanistan  1952     8425333      Asia    28.801  779.445314     1962
1     Afghanistan  1957     9240934      Asia    30.332  820.853030     1967
2     Afghanistan  1962    10267083      Asia    31.997  853.100710     1972
3     Afghanistan  1967    11537966      Asia    34.020  836.197138     1977
4     Afghanistan  1972    13079460      Asia    36.088  739.981106     1982
...           ...   ...         ...       ...       ...         ...      ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306     1997
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786     2002
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960     2007
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623     2012
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298     2017

[1704 rows x 7 columns]

In [56]:
# option 1
df2 = df.drop('year+10', axis=1) # return new df with col dropped
df2.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [57]:
df.head()

country  year  population continent  life_exp     gdp_cap  year+10
0  Afghanistan  1952     8425333      Asia    28.801  779.445314     1962
1  Afghanistan  1957     9240934      Asia    30.332  820.853030     1967
2  Afghanistan  1962    10267083      Asia    31.997  853.100710     1972
3  Afghanistan  1967    11537966      Asia    34.020  836.197138     1977
4  Afghanistan  1972    13079460      Asia    36.088  739.981106     1982

In [58]:
df.drop('year+10', axis=1, inplace = True)

In [60]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

### Q for break:

- remove year + 10 from df completely
- try overwriting existing column

In [63]:
# 2) create a new column from scratch
list1 = ["Sachin"]
df["User"] = list1

ValueError: Length of values (1) does not match length of index (1704)

In [68]:
# creating new col User
new_list = ["Sachin" for i in range(df.shape[0])]
df["User"] = new_list
df.head()

country  year  population continent  life_exp     gdp_cap    User
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin

In [77]:
df['year2'] = df['year']
df.head()

country  year  population continent  life_exp     gdp_cap      User  \
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin 0   
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin 1   
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin 2   
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin 3   
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin 4   

   year2  
0   1952  
1   1957  
2   1962  
3   1967  
4   1972

In [69]:
# overwrite col user
new_list = [f"Sachin {i}" for i in range(df.shape[0])]
df["User"] = new_list
df.head()

country  year  population continent  life_exp     gdp_cap      User
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin 0
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin 1
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin 2
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin 3
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin 4

In [70]:
df['year'] + df['population'] # element wise operation on two series

0        8427285
1        9242891
2       10269045
3       11539933
4       13081432
          ...   
1699     9218405
1700    10706332
1701    11406945
1702    11928565
1703    12313150
Length: 1704, dtype: int64

In [74]:
df.columns[:5]

Index(['country', 'year', 'population', 'continent', 'life_exp'], dtype='object')

Given a dataframe consisting of 5 columns

In [ ]:
# df.drop(df.columns[2], axis=1)
# df.drop(df.columns[-3], axis=1)

- while creating or reading df from scratch, there can be duplicate headers

### operation on row indexes

In [78]:
df.index # access row index


RangeIndex(start=0, stop=1704, step=1)

In [79]:
# let's overwrite row index
df.index = [i + 100 for i in range(df.shape[0])]
df.index

Index([ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
       ...
       1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803],
      dtype='int64', length=1704)

In [80]:
df

country  year  population continent  life_exp     gdp_cap  \
100   Afghanistan  1952     8425333      Asia    28.801  779.445314   
101   Afghanistan  1957     9240934      Asia    30.332  820.853030   
102   Afghanistan  1962    10267083      Asia    31.997  853.100710   
103   Afghanistan  1967    11537966      Asia    34.020  836.197138   
104   Afghanistan  1972    13079460      Asia    36.088  739.981106   
...           ...   ...         ...       ...       ...         ...   
1799     Zimbabwe  1987     9216418    Africa    62.351  706.157306   
1800     Zimbabwe  1992    10704340    Africa    60.377  693.420786   
1801     Zimbabwe  1997    11404948    Africa    46.809  792.449960   
1802     Zimbabwe  2002    11926563    Africa    39.989  672.038623   
1803     Zimbabwe  2007    12311143    Africa    43.487  469.709298   

             User  year2  
100      Sachin 0   1952  
101      Sachin 1   1957  
102      Sachin 2   1962  
103      Sachin 3   1967  
104      Sachin 4   1972  
...           ...    ...  
1799  Sachin 1699   1987  
1800  Sachin 1700   1992  
1801  Sachin 1701   1997  
1802  Sachin 1702   2002  
1803  Sachin 1703   2007  

[1704 rows x 8 columns]

In [82]:
df[104] # defaults to column lookup

KeyError: 104

explicit: user defined indexing

In [87]:
df.loc[103] # row lookup: explicit index 4 row from top

country       Afghanistan
year                 1967
population       11537966
continent            Asia
life_exp            34.02
gdp_cap        836.197138
User             Sachin 3
year2                1967
Name: 103, dtype: object

# iloc: implicit indexing
- standard python style index

# implicit: pre-defined/inbuilt

In [88]:
df.iloc[3] # row lookup using implicit: inbuilt

country       Afghanistan
year                 1967
population       11537966
continent            Asia
life_exp            34.02
gdp_cap        836.197138
User             Sachin 3
year2                1967
Name: 103, dtype: object

Can we slicing using loc and iloc

In [89]:
df.loc[101: 104] # in slicing with loc, end is included

country  year  population continent  life_exp     gdp_cap      User  \
101  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin 1   
102  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin 2   
103  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin 3   
104  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin 4   

     year2  
101   1957  
102   1962  
103   1967  
104   1972

In [90]:
df.iloc[1: 4] # in slicing with loc, end is not included

country  year  population continent  life_exp     gdp_cap      User  \
101  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin 1   
102  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin 2   
103  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin 3   

     year2  
101   1957  
102   1962  
103   1967

In [92]:
df.loc[101: 104][['population' , 'country']]

population      country
101     9240934  Afghanistan
102    10267083  Afghanistan
103    11537966  Afghanistan
104    13079460  Afghanistan

In [93]:
df.loc[101: 104, ['population' , 'country']]

population      country
101     9240934  Afghanistan
102    10267083  Afghanistan
103    11537966  Afghanistan
104    13079460  Afghanistan

In [94]:
df.head()

country  year  population continent  life_exp     gdp_cap      User  \
100  Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin 0   
101  Afghanistan  1957     9240934      Asia    30.332  820.853030  Sachin 1   
102  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin 2   
103  Afghanistan  1967    11537966      Asia    34.020  836.197138  Sachin 3   
104  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin 4   

     year2  
100   1952  
101   1957  
102   1962  
103   1967  
104   1972

In [96]:
df.loc[101: 104, 'country':'population']

country  year  population
101  Afghanistan  1957     9240934
102  Afghanistan  1962    10267083
103  Afghanistan  1967    11537966
104  Afghanistan  1972    13079460

In [98]:
df.iloc[1: 5, 0:3]

country  year  population
101  Afghanistan  1957     9240934
102  Afghanistan  1962    10267083
103  Afghanistan  1967    11537966
104  Afghanistan  1972    13079460

In [100]:
demo = pd.Series(['a','b','c','d','e'], index=[1,5,3,7,3])
demo

1    a
5    b
3    c
7    d
3    e
dtype: object

In [101]:
demo.loc[1]

'a'

In [102]:
demo.loc[3]

3    c
3    e
dtype: object

In [103]:
demo.loc[1:3]

KeyError: 'Cannot get right slice bound for non-unique label: 3'

How to select records from 30th to 40th row for the last 3 columns using iloc?


In [106]:
df.iloc[29:40, -3:]

gdp_cap       User  year2
129  4910.416756  Sachin 29   1977
130  5745.160213  Sachin 30   1982
131  5681.358539  Sachin 31   1987
132  5023.216647  Sachin 32   1992
133  4797.295051  Sachin 33   1997
134  5288.040382  Sachin 34   2002
135  6223.367465  Sachin 35   2007
136  3520.610273  Sachin 36   1952
137  3827.940465  Sachin 37   1957
138  4269.276742  Sachin 38   1962
139  5522.776375  Sachin 39   1967

In [108]:
a = pd.Series(['a','b','c'], index=[1,2,2])
print(a[2])

2    b
2    c
dtype: object


### HW:
0) Index Setter
- Set one of the existing Column as index of df
 set country as index
- reset index to numerical values


1) Add the following row at the end into DataFrame:

```
new_row = {'country': 'India', 'year': 2000,'population':13500000, 'continent': "Asia", 'life_exp':37.08, 'gdp_cap':900.23}
```

2) Select a subset of Dataframe containing only first 4 rows and first 3 columns?(HINT: SAME AS SLICING IN 2D Numpy Array

3) Select All datapoints where life_exp > 50
(HINT: MASKING IN 2D Numpy Array)

4) Select all records of the country with Highest Life Expectancy in Asia Continent

In [109]:
demo = pd.Series(['a','b','c','d','e'], index=[1,5,3,7,3])
demo

1    a
5    b
3    c
7    d
3    e
dtype: object

In [112]:
demo.loc[5], demo[5] # use explicit index

('b', 'b')

In [113]:
demo.loc[3], demo[3]  # use explicit index

(3    c
 3    e
 dtype: object,
 3    c
 3    e
 dtype: object)

In [114]:
demo.iloc[3]

'd'

implicit can't be duplicated

- aws s3: cloud storage
- aws efs
- parquet files stored in local as well cloud
- query that dumpy data from db to some location
- blobstorage

In [118]:
# conditional generation
new_list=["Sachin" if (i%2==0) else "Naveen" for i in range(df.shape[0]) ]
len(new_list)

1704

In [119]:
df["User"]=new_list
df.head()

country  year  population continent  life_exp     gdp_cap    User  \
100  Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin   
101  Afghanistan  1957     9240934      Asia    30.332  820.853030  Naveen   
102  Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin   
103  Afghanistan  1967    11537966      Asia    34.020  836.197138  Naveen   
104  Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin   

     year2  
100   1952  
101   1957  
102   1962  
103   1967  
104   1972

In [120]:
df

country  year  population continent  life_exp     gdp_cap    User  \
100   Afghanistan  1952     8425333      Asia    28.801  779.445314  Sachin   
101   Afghanistan  1957     9240934      Asia    30.332  820.853030  Naveen   
102   Afghanistan  1962    10267083      Asia    31.997  853.100710  Sachin   
103   Afghanistan  1967    11537966      Asia    34.020  836.197138  Naveen   
104   Afghanistan  1972    13079460      Asia    36.088  739.981106  Sachin   
...           ...   ...         ...       ...       ...         ...     ...   
1799     Zimbabwe  1987     9216418    Africa    62.351  706.157306  Naveen   
1800     Zimbabwe  1992    10704340    Africa    60.377  693.420786  Sachin   
1801     Zimbabwe  1997    11404948    Africa    46.809  792.449960  Naveen   
1802     Zimbabwe  2002    11926563    Africa    39.989  672.038623  Sachin   
1803     Zimbabwe  2007    12311143    Africa    43.487  469.709298  Naveen   

      year2  
100    1952  
101    1957  
102    1962  
103    1967  
104    1972  
...     ...  
1799   1987  
1800   1992  
1801   1997  
1802   2002  
1803   2007  

[1704 rows x 8 columns]

In [122]:
df.shape # rows and cols

(1704, 8)

In [123]:
df.shape[0]

1704

In [124]:
df.shape[1]

8

In [127]:
import numpy as np
arr = np.array([[1,2, 3],
          [4,5,6]])

In [128]:
arr[0]

array([1, 2, 3])

In [129]:
arr[1]

array([4, 5, 6])

In [130]:
np.mean(arr, axis=0) # rowswise mean: mean on columns

array([2.5, 3.5, 4.5])

In [131]:
arr[0][0], arr[1][0]

(1, 4)

In [132]:
# 3 2
# 1 2
# 3 4
# 5 6

# # 4 x 2
# # (4 + 2) x (3 + 2) -> filled with zeroes

In [137]:
arr3 = np.array([[[0, 1],
             [2, 3]],

            [[4, 5],
             [6, 7]]])
arr3[0][0]

array([0, 1])

[[0, 1],
             [2, 3]]

             

In [134]:
arr2 =    np.array( [[0, 1],
             [2, 3]])

In [135]:
arr2[0]

array([0, 1])

In [138]:
list1 = [2,3,4,5]
list1[-1], list1[:-1]

(5, [2, 3, 4])

In [139]:
list1[0], list1[1:] = list1[-1], list1[:-1] # cyclic swap

In [140]:
list1

[5, 2, 3, 4]

In [144]:
arr3 = np.array([[[0, 1],
                 [2, 3]],  # index 0

                  [[4, 5],
                    [6, 7]]] ) # index 1
arr3[0]

array([[0, 1],
       [2, 3]])

In [145]:
arr3[0][0]

array([0, 1])

In [150]:
arr3[0][0][1]

1

In [154]:
arr3[1,:, :]

array([[4, 5],
       [6, 7]])